/**
 * Generates responsive WebP variants for all @assets images used by sims-homepage,
 * plus a TypeScript module that exports ResponsiveImage objects for each source file.
 *
 * Usage: node scripts/optimize-images.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const ASSETS = path.join(ROOT, 'attached_assets');
const OUT_DIR = path.join(ASSETS, 'optimized');
const SRC_ROOT = path.join(ROOT, 'artifacts', 'sims-homepage', 'src');
const GENERATED = path.join(
  ROOT,
  'artifacts',
  'sims-homepage',
  'src',
  'lib',
  'responsive-images.generated.ts',
);

const WIDTHS = [640, 1024, 1600];
const FULL_WIDTH = 1920;
const WEBP_QUALITY = 78;
const HERO_QUALITY = 82;

const ASSET_IMPORT_RE = /@assets\/([^'"`]+)/g;

function safeStem(filename) {
  return filename
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-zA-Z0-9_-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function exportName(stem) {
  let name = stem.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(name)) name = `img_${name}`;
  return name;
}

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      files.push(...(await walk(full)));
    } else if (/\.(ts|tsx|js|jsx)$/.test(entry.name)) {
      files.push(full);
    }
  }
  return files;
}

async function collectUsedAssets() {
  const sourcesPath = path.join(OUT_DIR, 'sources.json');
  const used = new Set();

  // Prefer locked source list so re-runs work after pages switch to optimized imports
  try {
    const locked = JSON.parse(await fs.readFile(sourcesPath, 'utf8'));
    if (Array.isArray(locked)) {
      for (const rel of locked) used.add(rel);
    }
  } catch {
    /* first run */
  }

  const files = await walk(SRC_ROOT);
  for (const file of files) {
    if (file.includes('responsive-images.generated')) continue;
    const text = await fs.readFile(file, 'utf8');
    for (const match of text.matchAll(ASSET_IMPORT_RE)) {
      const rel = match[1];
      if (rel.startsWith('optimized/')) continue;
      used.add(rel);
    }
  }
  return [...used].sort();
}

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function optimizeOne(relPath) {
  const input = path.join(ASSETS, relPath);
  try {
    await fs.access(input);
  } catch {
    console.warn(`  skip missing: ${relPath}`);
    return null;
  }

  const stem = safeStem(path.basename(relPath));
  const image = sharp(input, { failOn: 'none' });
  const meta = await image.metadata();
  const origW = meta.width || WIDTHS[WIDTHS.length - 1];
  const origH = meta.height || Math.round(origW * 0.75);
  const isOpaque = meta.hasAlpha !== true;

  const variants = [];
  for (const width of WIDTHS) {
    const targetW = Math.min(width, origW);
    const outName = `${stem}-${width}.webp`;
    const outPath = path.join(OUT_DIR, outName);
    await sharp(input, { failOn: 'none' })
      .rotate()
      .resize({ width: targetW, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 4, alphaQuality: 80 })
      .toFile(outPath);
    const stat = await fs.stat(outPath);
    variants.push({ width, file: outName, bytes: stat.size });
  }

  const fullW = Math.min(FULL_WIDTH, origW);
  const fullName = `${stem}-full.webp`;
  const fullPath = path.join(OUT_DIR, fullName);
  await sharp(input, { failOn: 'none' })
    .rotate()
    .resize({ width: fullW, withoutEnlargement: true })
    .webp({ quality: HERO_QUALITY, effort: 4, alphaQuality: 80 })
    .toFile(fullPath);
  const fullStat = await fs.stat(fullPath);

  // Intrinsic size of the default (largest display) variant
  const defaultWidth = Math.min(WIDTHS[WIDTHS.length - 1], origW);
  const defaultHeight = Math.round((origH / origW) * defaultWidth);

  return {
    source: relPath,
    stem,
    exportId: exportName(stem),
    width: defaultWidth,
    height: defaultHeight,
    origW,
    origH,
    hasAlpha: !isOpaque,
    variants,
    full: { width: fullW, file: fullName, bytes: fullStat.size },
  };
}

function generateTs(entries) {
  const lines = [
    '/* eslint-disable */',
    '/**',
    ' * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.',
    ' * Re-run: node scripts/optimize-images.mjs',
    ' */',
    '',
    "import type { ResponsiveImage } from './responsive-image';",
    '',
  ];

  for (const e of entries) {
    for (const v of e.variants) {
      lines.push(
        `import ${e.exportId}_${v.width} from '@assets/optimized/${v.file}';`,
      );
    }
    lines.push(
      `import ${e.exportId}_full from '@assets/optimized/${e.full.file}';`,
    );
  }

  lines.push('', 'function ri(');
  lines.push('  src: string,');
  lines.push('  srcSet: string,');
  lines.push('  width: number,');
  lines.push('  height: number,');
  lines.push('  fullSrc: string,');
  lines.push('): ResponsiveImage {');
  lines.push('  return { src, srcSet, width, height, fullSrc };');
  lines.push('}');
  lines.push('');

  for (const e of entries) {
    const defaultVar = e.variants[e.variants.length - 1];
    const srcSet = e.variants
      .map((v) => `\${${e.exportId}_${v.width}} ${v.width}w`)
      .join(', ');
    lines.push(`/** Optimized from ${e.source} (${e.origW}×${e.origH}) */`);
    lines.push(`export const ${e.exportId} = ri(`);
    lines.push(`  ${e.exportId}_${defaultVar.width},`);
    lines.push(`  \`${srcSet}\`,`);
    lines.push(`  ${e.width},`);
    lines.push(`  ${e.height},`);
    lines.push(`  ${e.exportId}_full,`);
    lines.push(`);`);
    lines.push('');
  }

  lines.push('/** Lookup by original attached_assets filename */');
  lines.push('export const RESPONSIVE_BY_SOURCE: Record<string, ResponsiveImage> = {');
  for (const e of entries) {
    lines.push(`  ${JSON.stringify(e.source)}: ${e.exportId},`);
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

async function main() {
  console.log('Collecting @assets imports…');
  const used = await collectUsedAssets();
  console.log(`Found ${used.length} source images`);

  await ensureDir(OUT_DIR);

  // Clear previous optimized webps to avoid orphans
  const existing = await fs.readdir(OUT_DIR).catch(() => []);
  for (const f of existing) {
    if (f.endsWith('.webp')) await fs.unlink(path.join(OUT_DIR, f));
  }

  const entries = [];
  let inBytes = 0;
  let outBytes = 0;

  for (const rel of used) {
    const input = path.join(ASSETS, rel);
    let inputSize = 0;
    try {
      inputSize = (await fs.stat(input)).size;
      inBytes += inputSize;
    } catch {
      /* handled in optimizeOne */
    }
    process.stdout.write(`  ${rel} (${(inputSize / 1e6).toFixed(2)} MB)… `);
    const result = await optimizeOne(rel);
    if (!result) {
      console.log('skipped');
      continue;
    }
    const totalOut =
      result.variants.reduce((s, v) => s + v.bytes, 0) + result.full.bytes;
    outBytes += totalOut;
    console.log(`→ ${(totalOut / 1e3).toFixed(0)} KB (${result.variants.length + 1} files)`);
    entries.push(result);
  }

  await fs.writeFile(GENERATED, generateTs(entries), 'utf8');
  await fs.writeFile(
    path.join(OUT_DIR, 'sources.json'),
    JSON.stringify(
      entries.map((e) => e.source),
      null,
      2,
    ) + '\n',
    'utf8',
  );
  console.log(`\nWrote ${GENERATED}`);
  console.log(
    `Payload: ${(inBytes / 1e6).toFixed(1)} MB originals → ${(outBytes / 1e6).toFixed(1)} MB optimized variants (all widths)`,
  );
  console.log(
    `Typical display asset ~${(outBytes / entries.length / 4 / 1e3).toFixed(0)} KB avg per size`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
