/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Re-run: node scripts/optimize-images.mjs
 */

import type { ResponsiveImage } from './responsive-image';

import img_12_640 from '@assets/optimized/12-640.webp';
import img_12_1024 from '@assets/optimized/12-1024.webp';
import img_12_1600 from '@assets/optimized/12-1600.webp';
import img_12_full from '@assets/optimized/12-full.webp';
import img_2_1_640 from '@assets/optimized/2-1-640.webp';
import img_2_1_1024 from '@assets/optimized/2-1-1024.webp';
import img_2_1_1600 from '@assets/optimized/2-1-1600.webp';
import img_2_1_full from '@assets/optimized/2-1-full.webp';
import img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_640 from '@assets/optimized/85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled-640.webp';
import img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_1024 from '@assets/optimized/85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled-1024.webp';
import img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_1600 from '@assets/optimized/85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled-1600.webp';
import img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_full from '@assets/optimized/85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled-full.webp';
import img_9_640 from '@assets/optimized/9-640.webp';
import img_9_1024 from '@assets/optimized/9-1024.webp';
import img_9_1600 from '@assets/optimized/9-1600.webp';
import img_9_full from '@assets/optimized/9-full.webp';
import DSC00007_640 from '@assets/optimized/DSC00007-640.webp';
import DSC00007_1024 from '@assets/optimized/DSC00007-1024.webp';
import DSC00007_1600 from '@assets/optimized/DSC00007-1600.webp';
import DSC00007_full from '@assets/optimized/DSC00007-full.webp';
import DSC00009_640 from '@assets/optimized/DSC00009-640.webp';
import DSC00009_1024 from '@assets/optimized/DSC00009-1024.webp';
import DSC00009_1600 from '@assets/optimized/DSC00009-1600.webp';
import DSC00009_full from '@assets/optimized/DSC00009-full.webp';
import DSC00050_640 from '@assets/optimized/DSC00050-640.webp';
import DSC00050_1024 from '@assets/optimized/DSC00050-1024.webp';
import DSC00050_1600 from '@assets/optimized/DSC00050-1600.webp';
import DSC00050_full from '@assets/optimized/DSC00050-full.webp';
import DSC00051_640 from '@assets/optimized/DSC00051-640.webp';
import DSC00051_1024 from '@assets/optimized/DSC00051-1024.webp';
import DSC00051_1600 from '@assets/optimized/DSC00051-1600.webp';
import DSC00051_full from '@assets/optimized/DSC00051-full.webp';
import DSC00066_scaled_640 from '@assets/optimized/DSC00066-scaled-640.webp';
import DSC00066_scaled_1024 from '@assets/optimized/DSC00066-scaled-1024.webp';
import DSC00066_scaled_1600 from '@assets/optimized/DSC00066-scaled-1600.webp';
import DSC00066_scaled_full from '@assets/optimized/DSC00066-scaled-full.webp';
import DSC00066_640 from '@assets/optimized/DSC00066-640.webp';
import DSC00066_1024 from '@assets/optimized/DSC00066-1024.webp';
import DSC00066_1600 from '@assets/optimized/DSC00066-1600.webp';
import DSC00066_full from '@assets/optimized/DSC00066-full.webp';
import DSC00075_scaled_640 from '@assets/optimized/DSC00075-scaled-640.webp';
import DSC00075_scaled_1024 from '@assets/optimized/DSC00075-scaled-1024.webp';
import DSC00075_scaled_1600 from '@assets/optimized/DSC00075-scaled-1600.webp';
import DSC00075_scaled_full from '@assets/optimized/DSC00075-scaled-full.webp';
import DSC00080_640 from '@assets/optimized/DSC00080-640.webp';
import DSC00080_1024 from '@assets/optimized/DSC00080-1024.webp';
import DSC00080_1600 from '@assets/optimized/DSC00080-1600.webp';
import DSC00080_full from '@assets/optimized/DSC00080-full.webp';
import DSC00096_640 from '@assets/optimized/DSC00096-640.webp';
import DSC00096_1024 from '@assets/optimized/DSC00096-1024.webp';
import DSC00096_1600 from '@assets/optimized/DSC00096-1600.webp';
import DSC00096_full from '@assets/optimized/DSC00096-full.webp';
import DSC00114_640 from '@assets/optimized/DSC00114-640.webp';
import DSC00114_1024 from '@assets/optimized/DSC00114-1024.webp';
import DSC00114_1600 from '@assets/optimized/DSC00114-1600.webp';
import DSC00114_full from '@assets/optimized/DSC00114-full.webp';
import DSC00116_640 from '@assets/optimized/DSC00116-640.webp';
import DSC00116_1024 from '@assets/optimized/DSC00116-1024.webp';
import DSC00116_1600 from '@assets/optimized/DSC00116-1600.webp';
import DSC00116_full from '@assets/optimized/DSC00116-full.webp';
import DSC00118_scaled_640 from '@assets/optimized/DSC00118-scaled-640.webp';
import DSC00118_scaled_1024 from '@assets/optimized/DSC00118-scaled-1024.webp';
import DSC00118_scaled_1600 from '@assets/optimized/DSC00118-scaled-1600.webp';
import DSC00118_scaled_full from '@assets/optimized/DSC00118-scaled-full.webp';
import DSC00123_640 from '@assets/optimized/DSC00123-640.webp';
import DSC00123_1024 from '@assets/optimized/DSC00123-1024.webp';
import DSC00123_1600 from '@assets/optimized/DSC00123-1600.webp';
import DSC00123_full from '@assets/optimized/DSC00123-full.webp';
import DSC00134_scaled_640 from '@assets/optimized/DSC00134-scaled-640.webp';
import DSC00134_scaled_1024 from '@assets/optimized/DSC00134-scaled-1024.webp';
import DSC00134_scaled_1600 from '@assets/optimized/DSC00134-scaled-1600.webp';
import DSC00134_scaled_full from '@assets/optimized/DSC00134-scaled-full.webp';
import DSC00159_640 from '@assets/optimized/DSC00159-640.webp';
import DSC00159_1024 from '@assets/optimized/DSC00159-1024.webp';
import DSC00159_1600 from '@assets/optimized/DSC00159-1600.webp';
import DSC00159_full from '@assets/optimized/DSC00159-full.webp';
import DSC00161_640 from '@assets/optimized/DSC00161-640.webp';
import DSC00161_1024 from '@assets/optimized/DSC00161-1024.webp';
import DSC00161_1600 from '@assets/optimized/DSC00161-1600.webp';
import DSC00161_full from '@assets/optimized/DSC00161-full.webp';
import DSC00171_640 from '@assets/optimized/DSC00171-640.webp';
import DSC00171_1024 from '@assets/optimized/DSC00171-1024.webp';
import DSC00171_1600 from '@assets/optimized/DSC00171-1600.webp';
import DSC00171_full from '@assets/optimized/DSC00171-full.webp';
import DSC00177_scaled_640 from '@assets/optimized/DSC00177-scaled-640.webp';
import DSC00177_scaled_1024 from '@assets/optimized/DSC00177-scaled-1024.webp';
import DSC00177_scaled_1600 from '@assets/optimized/DSC00177-scaled-1600.webp';
import DSC00177_scaled_full from '@assets/optimized/DSC00177-scaled-full.webp';
import DSC00188_640 from '@assets/optimized/DSC00188-640.webp';
import DSC00188_1024 from '@assets/optimized/DSC00188-1024.webp';
import DSC00188_1600 from '@assets/optimized/DSC00188-1600.webp';
import DSC00188_full from '@assets/optimized/DSC00188-full.webp';
import DSC00259_640 from '@assets/optimized/DSC00259-640.webp';
import DSC00259_1024 from '@assets/optimized/DSC00259-1024.webp';
import DSC00259_1600 from '@assets/optimized/DSC00259-1600.webp';
import DSC00259_full from '@assets/optimized/DSC00259-full.webp';
import DSC00273_640 from '@assets/optimized/DSC00273-640.webp';
import DSC00273_1024 from '@assets/optimized/DSC00273-1024.webp';
import DSC00273_1600 from '@assets/optimized/DSC00273-1600.webp';
import DSC00273_full from '@assets/optimized/DSC00273-full.webp';
import DSC00287_640 from '@assets/optimized/DSC00287-640.webp';
import DSC00287_1024 from '@assets/optimized/DSC00287-1024.webp';
import DSC00287_1600 from '@assets/optimized/DSC00287-1600.webp';
import DSC00287_full from '@assets/optimized/DSC00287-full.webp';
import DSC00312_640 from '@assets/optimized/DSC00312-640.webp';
import DSC00312_1024 from '@assets/optimized/DSC00312-1024.webp';
import DSC00312_1600 from '@assets/optimized/DSC00312-1600.webp';
import DSC00312_full from '@assets/optimized/DSC00312-full.webp';
import DSC00317_640 from '@assets/optimized/DSC00317-640.webp';
import DSC00317_1024 from '@assets/optimized/DSC00317-1024.webp';
import DSC00317_1600 from '@assets/optimized/DSC00317-1600.webp';
import DSC00317_full from '@assets/optimized/DSC00317-full.webp';
import DSC00338_640 from '@assets/optimized/DSC00338-640.webp';
import DSC00338_1024 from '@assets/optimized/DSC00338-1024.webp';
import DSC00338_1600 from '@assets/optimized/DSC00338-1600.webp';
import DSC00338_full from '@assets/optimized/DSC00338-full.webp';
import DSC00365_640 from '@assets/optimized/DSC00365-640.webp';
import DSC00365_1024 from '@assets/optimized/DSC00365-1024.webp';
import DSC00365_1600 from '@assets/optimized/DSC00365-1600.webp';
import DSC00365_full from '@assets/optimized/DSC00365-full.webp';
import DSC00382_640 from '@assets/optimized/DSC00382-640.webp';
import DSC00382_1024 from '@assets/optimized/DSC00382-1024.webp';
import DSC00382_1600 from '@assets/optimized/DSC00382-1600.webp';
import DSC00382_full from '@assets/optimized/DSC00382-full.webp';
import DSC00408_640 from '@assets/optimized/DSC00408-640.webp';
import DSC00408_1024 from '@assets/optimized/DSC00408-1024.webp';
import DSC00408_1600 from '@assets/optimized/DSC00408-1600.webp';
import DSC00408_full from '@assets/optimized/DSC00408-full.webp';
import DSC00413_640 from '@assets/optimized/DSC00413-640.webp';
import DSC00413_1024 from '@assets/optimized/DSC00413-1024.webp';
import DSC00413_1600 from '@assets/optimized/DSC00413-1600.webp';
import DSC00413_full from '@assets/optimized/DSC00413-full.webp';
import DSC00434_640 from '@assets/optimized/DSC00434-640.webp';
import DSC00434_1024 from '@assets/optimized/DSC00434-1024.webp';
import DSC00434_1600 from '@assets/optimized/DSC00434-1600.webp';
import DSC00434_full from '@assets/optimized/DSC00434-full.webp';
import DSC00446_640 from '@assets/optimized/DSC00446-640.webp';
import DSC00446_1024 from '@assets/optimized/DSC00446-1024.webp';
import DSC00446_1600 from '@assets/optimized/DSC00446-1600.webp';
import DSC00446_full from '@assets/optimized/DSC00446-full.webp';
import DSC00447_640 from '@assets/optimized/DSC00447-640.webp';
import DSC00447_1024 from '@assets/optimized/DSC00447-1024.webp';
import DSC00447_1600 from '@assets/optimized/DSC00447-1600.webp';
import DSC00447_full from '@assets/optimized/DSC00447-full.webp';
import DSC00450_640 from '@assets/optimized/DSC00450-640.webp';
import DSC00450_1024 from '@assets/optimized/DSC00450-1024.webp';
import DSC00450_1600 from '@assets/optimized/DSC00450-1600.webp';
import DSC00450_full from '@assets/optimized/DSC00450-full.webp';
import DSC00456_640 from '@assets/optimized/DSC00456-640.webp';
import DSC00456_1024 from '@assets/optimized/DSC00456-1024.webp';
import DSC00456_1600 from '@assets/optimized/DSC00456-1600.webp';
import DSC00456_full from '@assets/optimized/DSC00456-full.webp';
import DSC00484_640 from '@assets/optimized/DSC00484-640.webp';
import DSC00484_1024 from '@assets/optimized/DSC00484-1024.webp';
import DSC00484_1600 from '@assets/optimized/DSC00484-1600.webp';
import DSC00484_full from '@assets/optimized/DSC00484-full.webp';
import DSC00503_640 from '@assets/optimized/DSC00503-640.webp';
import DSC00503_1024 from '@assets/optimized/DSC00503-1024.webp';
import DSC00503_1600 from '@assets/optimized/DSC00503-1600.webp';
import DSC00503_full from '@assets/optimized/DSC00503-full.webp';
import DSC00555_640 from '@assets/optimized/DSC00555-640.webp';
import DSC00555_1024 from '@assets/optimized/DSC00555-1024.webp';
import DSC00555_1600 from '@assets/optimized/DSC00555-1600.webp';
import DSC00555_full from '@assets/optimized/DSC00555-full.webp';
import DSC00578_640 from '@assets/optimized/DSC00578-640.webp';
import DSC00578_1024 from '@assets/optimized/DSC00578-1024.webp';
import DSC00578_1600 from '@assets/optimized/DSC00578-1600.webp';
import DSC00578_full from '@assets/optimized/DSC00578-full.webp';
import DSC00603_640 from '@assets/optimized/DSC00603-640.webp';
import DSC00603_1024 from '@assets/optimized/DSC00603-1024.webp';
import DSC00603_1600 from '@assets/optimized/DSC00603-1600.webp';
import DSC00603_full from '@assets/optimized/DSC00603-full.webp';
import DSC00646_640 from '@assets/optimized/DSC00646-640.webp';
import DSC00646_1024 from '@assets/optimized/DSC00646-1024.webp';
import DSC00646_1600 from '@assets/optimized/DSC00646-1600.webp';
import DSC00646_full from '@assets/optimized/DSC00646-full.webp';
import DSC00697_640 from '@assets/optimized/DSC00697-640.webp';
import DSC00697_1024 from '@assets/optimized/DSC00697-1024.webp';
import DSC00697_1600 from '@assets/optimized/DSC00697-1600.webp';
import DSC00697_full from '@assets/optimized/DSC00697-full.webp';
import DSC00698_1_scaled_640 from '@assets/optimized/DSC00698-1-scaled-640.webp';
import DSC00698_1_scaled_1024 from '@assets/optimized/DSC00698-1-scaled-1024.webp';
import DSC00698_1_scaled_1600 from '@assets/optimized/DSC00698-1-scaled-1600.webp';
import DSC00698_1_scaled_full from '@assets/optimized/DSC00698-1-scaled-full.webp';
import DSC00738_640 from '@assets/optimized/DSC00738-640.webp';
import DSC00738_1024 from '@assets/optimized/DSC00738-1024.webp';
import DSC00738_1600 from '@assets/optimized/DSC00738-1600.webp';
import DSC00738_full from '@assets/optimized/DSC00738-full.webp';
import DSC00836_640 from '@assets/optimized/DSC00836-640.webp';
import DSC00836_1024 from '@assets/optimized/DSC00836-1024.webp';
import DSC00836_1600 from '@assets/optimized/DSC00836-1600.webp';
import DSC00836_full from '@assets/optimized/DSC00836-full.webp';
import DSC00840_scaled_640 from '@assets/optimized/DSC00840-scaled-640.webp';
import DSC00840_scaled_1024 from '@assets/optimized/DSC00840-scaled-1024.webp';
import DSC00840_scaled_1600 from '@assets/optimized/DSC00840-scaled-1600.webp';
import DSC00840_scaled_full from '@assets/optimized/DSC00840-scaled-full.webp';
import DSC05081_640 from '@assets/optimized/DSC05081-640.webp';
import DSC05081_1024 from '@assets/optimized/DSC05081-1024.webp';
import DSC05081_1600 from '@assets/optimized/DSC05081-1600.webp';
import DSC05081_full from '@assets/optimized/DSC05081-full.webp';
import DSC05087_640 from '@assets/optimized/DSC05087-640.webp';
import DSC05087_1024 from '@assets/optimized/DSC05087-1024.webp';
import DSC05087_1600 from '@assets/optimized/DSC05087-1600.webp';
import DSC05087_full from '@assets/optimized/DSC05087-full.webp';
import DSC05089_640 from '@assets/optimized/DSC05089-640.webp';
import DSC05089_1024 from '@assets/optimized/DSC05089-1024.webp';
import DSC05089_1600 from '@assets/optimized/DSC05089-1600.webp';
import DSC05089_full from '@assets/optimized/DSC05089-full.webp';
import DSC05112_640 from '@assets/optimized/DSC05112-640.webp';
import DSC05112_1024 from '@assets/optimized/DSC05112-1024.webp';
import DSC05112_1600 from '@assets/optimized/DSC05112-1600.webp';
import DSC05112_full from '@assets/optimized/DSC05112-full.webp';
import DSC05112_hero_640 from '@assets/optimized/DSC05112-hero-640.webp';
import DSC05112_hero_1024 from '@assets/optimized/DSC05112-hero-1024.webp';
import DSC05112_hero_1600 from '@assets/optimized/DSC05112-hero-1600.webp';
import DSC05112_hero_full from '@assets/optimized/DSC05112-hero-full.webp';
import DSC05175_640 from '@assets/optimized/DSC05175-640.webp';
import DSC05175_1024 from '@assets/optimized/DSC05175-1024.webp';
import DSC05175_1600 from '@assets/optimized/DSC05175-1600.webp';
import DSC05175_full from '@assets/optimized/DSC05175-full.webp';
import DSC05124_640 from '@assets/optimized/DSC05124-640.webp';
import DSC05124_1024 from '@assets/optimized/DSC05124-1024.webp';
import DSC05124_1600 from '@assets/optimized/DSC05124-1600.webp';
import DSC05124_full from '@assets/optimized/DSC05124-full.webp';
import DSC05124_cleanup_640 from '@assets/optimized/DSC05124-cleanup-640.webp';
import DSC05124_cleanup_1024 from '@assets/optimized/DSC05124-cleanup-1024.webp';
import DSC05124_cleanup_1600 from '@assets/optimized/DSC05124-cleanup-1600.webp';
import DSC05124_cleanup_full from '@assets/optimized/DSC05124-cleanup-full.webp';
import DSC05126_640 from '@assets/optimized/DSC05126-640.webp';
import DSC05126_1024 from '@assets/optimized/DSC05126-1024.webp';
import DSC05126_1600 from '@assets/optimized/DSC05126-1600.webp';
import DSC05126_full from '@assets/optimized/DSC05126-full.webp';
import DSC05143_640 from '@assets/optimized/DSC05143-640.webp';
import DSC05143_1024 from '@assets/optimized/DSC05143-1024.webp';
import DSC05143_1600 from '@assets/optimized/DSC05143-1600.webp';
import DSC05143_full from '@assets/optimized/DSC05143-full.webp';
import DSC05150_640 from '@assets/optimized/DSC05150-640.webp';
import DSC05150_1024 from '@assets/optimized/DSC05150-1024.webp';
import DSC05150_1600 from '@assets/optimized/DSC05150-1600.webp';
import DSC05150_full from '@assets/optimized/DSC05150-full.webp';
import DSC05222_640 from '@assets/optimized/DSC05222-640.webp';
import DSC05222_1024 from '@assets/optimized/DSC05222-1024.webp';
import DSC05222_1600 from '@assets/optimized/DSC05222-1600.webp';
import DSC05222_full from '@assets/optimized/DSC05222-full.webp';
import Shushila_Institute_Of_removebg_preview_1_e1743436624699_640 from '@assets/optimized/Shushila_Institute_Of-removebg-preview-1-e1743436624699-640.webp';
import Shushila_Institute_Of_removebg_preview_1_e1743436624699_1024 from '@assets/optimized/Shushila_Institute_Of-removebg-preview-1-e1743436624699-1024.webp';
import Shushila_Institute_Of_removebg_preview_1_e1743436624699_1600 from '@assets/optimized/Shushila_Institute_Of-removebg-preview-1-e1743436624699-1600.webp';
import Shushila_Institute_Of_removebg_preview_1_e1743436624699_full from '@assets/optimized/Shushila_Institute_Of-removebg-preview-1-e1743436624699-full.webp';
import awards_blood_donation_640 from '@assets/optimized/awards-blood-donation-640.webp';
import awards_blood_donation_1024 from '@assets/optimized/awards-blood-donation-1024.webp';
import awards_blood_donation_1600 from '@assets/optimized/awards-blood-donation-1600.webp';
import awards_blood_donation_full from '@assets/optimized/awards-blood-donation-full.webp';
import awards_campus_facade_640 from '@assets/optimized/awards-campus-facade-640.webp';
import awards_campus_facade_1024 from '@assets/optimized/awards-campus-facade-1024.webp';
import awards_campus_facade_1600 from '@assets/optimized/awards-campus-facade-1600.webp';
import awards_campus_facade_full from '@assets/optimized/awards-campus-facade-full.webp';
import awards_campus_run_team_640 from '@assets/optimized/awards-campus-run-team-640.webp';
import awards_campus_run_team_1024 from '@assets/optimized/awards-campus-run-team-1024.webp';
import awards_campus_run_team_1600 from '@assets/optimized/awards-campus-run-team-1600.webp';
import awards_campus_run_team_full from '@assets/optimized/awards-campus-run-team-full.webp';
import awards_ceremony_group_640 from '@assets/optimized/awards-ceremony-group-640.webp';
import awards_ceremony_group_1024 from '@assets/optimized/awards-ceremony-group-1024.webp';
import awards_ceremony_group_1600 from '@assets/optimized/awards-ceremony-group-1600.webp';
import awards_ceremony_group_full from '@assets/optimized/awards-ceremony-group-full.webp';
import awards_doctors_day_collage_640 from '@assets/optimized/awards-doctors-day-collage-640.webp';
import awards_doctors_day_collage_1024 from '@assets/optimized/awards-doctors-day-collage-1024.webp';
import awards_doctors_day_collage_1600 from '@assets/optimized/awards-doctors-day-collage-1600.webp';
import awards_doctors_day_collage_full from '@assets/optimized/awards-doctors-day-collage-full.webp';
import awards_tb_awareness_640 from '@assets/optimized/awards-tb-awareness-640.webp';
import awards_tb_awareness_1024 from '@assets/optimized/awards-tb-awareness-1024.webp';
import awards_tb_awareness_1600 from '@assets/optimized/awards-tb-awareness-1600.webp';
import awards_tb_awareness_full from '@assets/optimized/awards-tb-awareness-full.webp';
import awards_tb_day_group_640 from '@assets/optimized/awards-tb-day-group-640.webp';
import awards_tb_day_group_1024 from '@assets/optimized/awards-tb-day-group-1024.webp';
import awards_tb_day_group_1600 from '@assets/optimized/awards-tb-day-group-1600.webp';
import awards_tb_day_group_full from '@assets/optimized/awards-tb-day-group-full.webp';
import awards_tree_plantation_nursery_640 from '@assets/optimized/awards-tree-plantation-nursery-640.webp';
import awards_tree_plantation_nursery_1024 from '@assets/optimized/awards-tree-plantation-nursery-1024.webp';
import awards_tree_plantation_nursery_1600 from '@assets/optimized/awards-tree-plantation-nursery-1600.webp';
import awards_tree_plantation_nursery_full from '@assets/optimized/awards-tree-plantation-nursery-full.webp';
import chairman_640 from '@assets/optimized/chairman-640.webp';
import chairman_1024 from '@assets/optimized/chairman-1024.webp';
import chairman_1600 from '@assets/optimized/chairman-1600.webp';
import chairman_full from '@assets/optimized/chairman-full.webp';
import coo_640 from '@assets/optimized/coo-640.webp';
import coo_1024 from '@assets/optimized/coo-1024.webp';
import coo_1600 from '@assets/optimized/coo-1600.webp';
import coo_full from '@assets/optimized/coo-full.webp';
import director_640 from '@assets/optimized/director-640.webp';
import director_1024 from '@assets/optimized/director-1024.webp';
import director_1600 from '@assets/optimized/director-1600.webp';
import director_full from '@assets/optimized/director-full.webp';
import hnb_umeu_logo_640 from '@assets/optimized/hnb-umeu-logo-640.webp';
import hnb_umeu_logo_1024 from '@assets/optimized/hnb-umeu-logo-1024.webp';
import hnb_umeu_logo_1600 from '@assets/optimized/hnb-umeu-logo-1600.webp';
import hnb_umeu_logo_full from '@assets/optimized/hnb-umeu-logo-full.webp';
import labs_collage_640 from '@assets/optimized/labs-collage-640.webp';
import labs_collage_1024 from '@assets/optimized/labs-collage-1024.webp';
import labs_collage_1600 from '@assets/optimized/labs-collage-1600.webp';
import labs_collage_full from '@assets/optimized/labs-collage-full.webp';
import transport_bus_collage_640 from '@assets/optimized/transport-bus-collage-640.webp';
import transport_bus_collage_1024 from '@assets/optimized/transport-bus-collage-1024.webp';
import transport_bus_collage_1600 from '@assets/optimized/transport-bus-collage-1600.webp';
import transport_bus_collage_full from '@assets/optimized/transport-bus-collage-full.webp';
import transport_route_coverage_map_640 from '@assets/optimized/transport-route-coverage-map-640.webp';
import transport_route_coverage_map_1024 from '@assets/optimized/transport-route-coverage-map-1024.webp';
import transport_route_coverage_map_1600 from '@assets/optimized/transport-route-coverage-map-1600.webp';
import transport_route_coverage_map_full from '@assets/optimized/transport-route-coverage-map-full.webp';
import hero_campus_life_collage_640 from '@assets/optimized/hero-campus-life-collage-640.webp';
import hero_campus_life_collage_1024 from '@assets/optimized/hero-campus-life-collage-1024.webp';
import hero_campus_life_collage_1600 from '@assets/optimized/hero-campus-life-collage-1600.webp';
import hero_campus_life_collage_full from '@assets/optimized/hero-campus-life-collage-full.webp';
import hero_campus_life_collage_v2_640 from '@assets/optimized/hero-campus-life-collage-v2-640.webp';
import hero_campus_life_collage_v2_1024 from '@assets/optimized/hero-campus-life-collage-v2-1024.webp';
import hero_campus_life_collage_v2_1600 from '@assets/optimized/hero-campus-life-collage-v2-1600.webp';
import hero_campus_life_collage_v2_full from '@assets/optimized/hero-campus-life-collage-v2-full.webp';
import logo_transparent_640 from '@assets/optimized/logo-transparent-640.webp';
import logo_transparent_1024 from '@assets/optimized/logo-transparent-1024.webp';
import logo_transparent_1600 from '@assets/optimized/logo-transparent-1600.webp';
import logo_transparent_full from '@assets/optimized/logo-transparent-full.webp';
import logo_watermark_640 from '@assets/optimized/logo-watermark-640.webp';
import logo_watermark_1024 from '@assets/optimized/logo-watermark-1024.webp';
import logo_watermark_1600 from '@assets/optimized/logo-watermark-1600.webp';
import logo_watermark_full from '@assets/optimized/logo-watermark-full.webp';
import logo_640 from '@assets/optimized/logo-640.webp';
import logo_1024 from '@assets/optimized/logo-1024.webp';
import logo_1600 from '@assets/optimized/logo-1600.webp';
import logo_full from '@assets/optimized/logo-full.webp';
import mission_skills_lab_640 from '@assets/optimized/mission-skills-lab-640.webp';
import mission_skills_lab_1024 from '@assets/optimized/mission-skills-lab-1024.webp';
import mission_skills_lab_1600 from '@assets/optimized/mission-skills-lab-1600.webp';
import mission_skills_lab_full from '@assets/optimized/mission-skills-lab-full.webp';
import principal_640 from '@assets/optimized/principal-640.webp';
import principal_1024 from '@assets/optimized/principal-1024.webp';
import principal_1600 from '@assets/optimized/principal-1600.webp';
import principal_full from '@assets/optimized/principal-full.webp';
import sims_campus_entrance_640 from '@assets/optimized/sims-campus-entrance-640.webp';
import sims_campus_entrance_1024 from '@assets/optimized/sims-campus-entrance-1024.webp';
import sims_campus_entrance_1600 from '@assets/optimized/sims-campus-entrance-1600.webp';
import sims_campus_entrance_full from '@assets/optimized/sims-campus-entrance-full.webp';
import sims_campus_lobby_640 from '@assets/optimized/sims-campus-lobby-640.webp';
import sims_campus_lobby_1024 from '@assets/optimized/sims-campus-lobby-1024.webp';
import sims_campus_lobby_1600 from '@assets/optimized/sims-campus-lobby-1600.webp';
import sims_campus_lobby_full from '@assets/optimized/sims-campus-lobby-full.webp';
import sims_campus_signage_640 from '@assets/optimized/sims-campus-signage-640.webp';
import sims_campus_signage_1024 from '@assets/optimized/sims-campus-signage-1024.webp';
import sims_campus_signage_1600 from '@assets/optimized/sims-campus-signage-1600.webp';
import sims_campus_signage_full from '@assets/optimized/sims-campus-signage-full.webp';
import vice_chairperson_640 from '@assets/optimized/vice-chairperson-640.webp';
import vice_chairperson_1024 from '@assets/optimized/vice-chairperson-1024.webp';
import vice_chairperson_1600 from '@assets/optimized/vice-chairperson-1600.webp';
import vice_chairperson_full from '@assets/optimized/vice-chairperson-full.webp';
import vision_inclusive_classroom_640 from '@assets/optimized/vision-inclusive-classroom-640.webp';
import vision_inclusive_classroom_1024 from '@assets/optimized/vision-inclusive-classroom-1024.webp';
import vision_inclusive_classroom_1600 from '@assets/optimized/vision-inclusive-classroom-1600.webp';
import vision_inclusive_classroom_full from '@assets/optimized/vision-inclusive-classroom-full.webp';
import awards_eia_plaque_640 from '@assets/optimized/awards-eia-plaque-640.webp';
import awards_eia_plaque_full from '@assets/optimized/awards-eia-plaque-full.webp';
import awards_trophy_presentation_640 from '@assets/optimized/awards-trophy-presentation-640.webp';
import awards_trophy_presentation_full from '@assets/optimized/awards-trophy-presentation-full.webp';
import awards_campus_certificate_1_640 from '@assets/optimized/awards-campus-certificate-1-640.webp';
import awards_campus_certificate_1_full from '@assets/optimized/awards-campus-certificate-1-full.webp';
import awards_campus_certificate_2_640 from '@assets/optimized/awards-campus-certificate-2-640.webp';
import awards_campus_certificate_2_full from '@assets/optimized/awards-campus-certificate-2-full.webp';
import awards_campus_certificate_3_640 from '@assets/optimized/awards-campus-certificate-3-640.webp';
import awards_campus_certificate_3_full from '@assets/optimized/awards-campus-certificate-3-full.webp';
import awards_faculty_student_group_640 from '@assets/optimized/awards-faculty-student-group-640.webp';
import awards_faculty_student_group_full from '@assets/optimized/awards-faculty-student-group-full.webp';
import awards_tree_plantation_drive_640 from '@assets/optimized/awards-tree-plantation-drive-640.webp';
import awards_tree_plantation_drive_full from '@assets/optimized/awards-tree-plantation-drive-full.webp';
import awards_emerging_uttarakhand_640 from '@assets/optimized/awards-emerging-uttarakhand-640.webp';
import awards_emerging_uttarakhand_full from '@assets/optimized/awards-emerging-uttarakhand-full.webp';

function ri(
  src: string,
  srcSet: string,
  width: number,
  height: number,
  fullSrc: string,
): ResponsiveImage {
  return { src, srcSet, width, height, fullSrc };
}

/** Optimized from 12.png (1000×1000) */
export const img_12 = ri(
  img_12_1600,
  `${img_12_640} 640w, ${img_12_1024} 1024w, ${img_12_1600} 1600w`,
  1000,
  1000,
  img_12_full,
);

/** Optimized from 2 (1).png (1000×1000) */
export const img_2_1 = ri(
  img_2_1_1600,
  `${img_2_1_640} 640w, ${img_2_1_1024} 1024w, ${img_2_1_1600} 1600w`,
  1000,
  1000,
  img_2_1_full,
);

/** Optimized from 85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled.jpg (2560×1920) */
export const img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled = ri(
  img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_1600,
  `${img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_640} 640w, ${img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_1024} 1024w, ${img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_1600} 1600w`,
  1600,
  1200,
  img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled_full,
);

/** Optimized from 9.png (1000×1000) */
export const img_9 = ri(
  img_9_1600,
  `${img_9_640} 640w, ${img_9_1024} 1024w, ${img_9_1600} 1600w`,
  1000,
  1000,
  img_9_full,
);

/** Optimized from DSC00007.jpg (6000×4000) */
export const DSC00007 = ri(
  DSC00007_1600,
  `${DSC00007_640} 640w, ${DSC00007_1024} 1024w, ${DSC00007_1600} 1600w`,
  1600,
  1067,
  DSC00007_full,
);

/** Optimized from DSC00009.jpg (6000×4000) */
export const DSC00009 = ri(
  DSC00009_1600,
  `${DSC00009_640} 640w, ${DSC00009_1024} 1024w, ${DSC00009_1600} 1600w`,
  1600,
  1067,
  DSC00009_full,
);

/** Optimized from DSC00050.jpg (5885×3923) */
export const DSC00050 = ri(
  DSC00050_1600,
  `${DSC00050_640} 640w, ${DSC00050_1024} 1024w, ${DSC00050_1600} 1600w`,
  1600,
  1067,
  DSC00050_full,
);

/** Optimized from DSC00051.jpg (6000×4000) */
export const DSC00051 = ri(
  DSC00051_1600,
  `${DSC00051_640} 640w, ${DSC00051_1024} 1024w, ${DSC00051_1600} 1600w`,
  1600,
  1067,
  DSC00051_full,
);

/** Optimized from DSC00066-scaled.jpg (2560×1707) */
export const DSC00066_scaled = ri(
  DSC00066_scaled_1600,
  `${DSC00066_scaled_640} 640w, ${DSC00066_scaled_1024} 1024w, ${DSC00066_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00066_scaled_full,
);

/** Optimized from DSC00066.jpg (5901×3934) */
export const DSC00066 = ri(
  DSC00066_1600,
  `${DSC00066_640} 640w, ${DSC00066_1024} 1024w, ${DSC00066_1600} 1600w`,
  1600,
  1067,
  DSC00066_full,
);

/** Optimized from DSC00075-scaled.jpg (2560×1707) */
export const DSC00075_scaled = ri(
  DSC00075_scaled_1600,
  `${DSC00075_scaled_640} 640w, ${DSC00075_scaled_1024} 1024w, ${DSC00075_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00075_scaled_full,
);

/** Optimized from DSC00080.jpg (4000×6000) */
export const DSC00080 = ri(
  DSC00080_1600,
  `${DSC00080_640} 640w, ${DSC00080_1024} 1024w, ${DSC00080_1600} 1600w`,
  1600,
  2400,
  DSC00080_full,
);

/** Optimized from DSC00096.jpg (4000×6000) */
export const DSC00096 = ri(
  DSC00096_1600,
  `${DSC00096_640} 640w, ${DSC00096_1024} 1024w, ${DSC00096_1600} 1600w`,
  1600,
  2400,
  DSC00096_full,
);

/** Optimized from DSC00114.jpg (6000×4000) */
export const DSC00114 = ri(
  DSC00114_1600,
  `${DSC00114_640} 640w, ${DSC00114_1024} 1024w, ${DSC00114_1600} 1600w`,
  1600,
  1067,
  DSC00114_full,
);

/** Optimized from DSC00116.jpg (4000×6000) */
export const DSC00116 = ri(
  DSC00116_1600,
  `${DSC00116_640} 640w, ${DSC00116_1024} 1024w, ${DSC00116_1600} 1600w`,
  1600,
  2400,
  DSC00116_full,
);

/** Optimized from DSC00118-scaled.jpg (2560×1707) */
export const DSC00118_scaled = ri(
  DSC00118_scaled_1600,
  `${DSC00118_scaled_640} 640w, ${DSC00118_scaled_1024} 1024w, ${DSC00118_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00118_scaled_full,
);

/** Optimized from DSC00123.jpg (6000×4000) */
export const DSC00123 = ri(
  DSC00123_1600,
  `${DSC00123_640} 640w, ${DSC00123_1024} 1024w, ${DSC00123_1600} 1600w`,
  1600,
  1067,
  DSC00123_full,
);

/** Optimized from DSC00134-scaled.jpg (1707×2560) */
export const DSC00134_scaled = ri(
  DSC00134_scaled_1600,
  `${DSC00134_scaled_640} 640w, ${DSC00134_scaled_1024} 1024w, ${DSC00134_scaled_1600} 1600w`,
  1600,
  2400,
  DSC00134_scaled_full,
);

/** Optimized from DSC00159.jpg (6000×4000) */
export const DSC00159 = ri(
  DSC00159_1600,
  `${DSC00159_640} 640w, ${DSC00159_1024} 1024w, ${DSC00159_1600} 1600w`,
  1600,
  1067,
  DSC00159_full,
);

/** Optimized from DSC00161.jpg (6000×4000) */
export const DSC00161 = ri(
  DSC00161_1600,
  `${DSC00161_640} 640w, ${DSC00161_1024} 1024w, ${DSC00161_1600} 1600w`,
  1600,
  1067,
  DSC00161_full,
);

/** Optimized from DSC00171.jpg (6000×4000) */
export const DSC00171 = ri(
  DSC00171_1600,
  `${DSC00171_640} 640w, ${DSC00171_1024} 1024w, ${DSC00171_1600} 1600w`,
  1600,
  1067,
  DSC00171_full,
);

/** Optimized from DSC00177-scaled.jpg (2560×1707) */
export const DSC00177_scaled = ri(
  DSC00177_scaled_1600,
  `${DSC00177_scaled_640} 640w, ${DSC00177_scaled_1024} 1024w, ${DSC00177_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00177_scaled_full,
);

/** Optimized from DSC00188.jpg (6000×4000) */
export const DSC00188 = ri(
  DSC00188_1600,
  `${DSC00188_640} 640w, ${DSC00188_1024} 1024w, ${DSC00188_1600} 1600w`,
  1600,
  1067,
  DSC00188_full,
);

/** Optimized from DSC00259.jpg (6000×4000) */
export const DSC00259 = ri(
  DSC00259_1600,
  `${DSC00259_640} 640w, ${DSC00259_1024} 1024w, ${DSC00259_1600} 1600w`,
  1600,
  1067,
  DSC00259_full,
);

/** Optimized from DSC00273.jpg (5696×3797) */
export const DSC00273 = ri(
  DSC00273_1600,
  `${DSC00273_640} 640w, ${DSC00273_1024} 1024w, ${DSC00273_1600} 1600w`,
  1600,
  1067,
  DSC00273_full,
);

/** Optimized from DSC00287.jpg (6988×4659) */
export const DSC00287 = ri(
  DSC00287_1600,
  `${DSC00287_640} 640w, ${DSC00287_1024} 1024w, ${DSC00287_1600} 1600w`,
  1600,
  1067,
  DSC00287_full,
);

/** Optimized from DSC00312.jpg (7008×4672) */
export const DSC00312 = ri(
  DSC00312_1600,
  `${DSC00312_640} 640w, ${DSC00312_1024} 1024w, ${DSC00312_1600} 1600w`,
  1600,
  1067,
  DSC00312_full,
);

/** Optimized from DSC00317.jpg (6000×4000) */
export const DSC00317 = ri(
  DSC00317_1600,
  `${DSC00317_640} 640w, ${DSC00317_1024} 1024w, ${DSC00317_1600} 1600w`,
  1600,
  1067,
  DSC00317_full,
);

/** Optimized from DSC00338.jpg (7008×4672) */
export const DSC00338 = ri(
  DSC00338_1600,
  `${DSC00338_640} 640w, ${DSC00338_1024} 1024w, ${DSC00338_1600} 1600w`,
  1600,
  1067,
  DSC00338_full,
);

/** Optimized from DSC00365.jpg (7008×4672) */
export const DSC00365 = ri(
  DSC00365_1600,
  `${DSC00365_640} 640w, ${DSC00365_1024} 1024w, ${DSC00365_1600} 1600w`,
  1600,
  1067,
  DSC00365_full,
);

/** Optimized from DSC00382.jpg (6000×4000) */
export const DSC00382 = ri(
  DSC00382_1600,
  `${DSC00382_640} 640w, ${DSC00382_1024} 1024w, ${DSC00382_1600} 1600w`,
  1600,
  1067,
  DSC00382_full,
);

/** Optimized from DSC00408.jpg (6000×4000) */
export const DSC00408 = ri(
  DSC00408_1600,
  `${DSC00408_640} 640w, ${DSC00408_1024} 1024w, ${DSC00408_1600} 1600w`,
  1600,
  1067,
  DSC00408_full,
);

/** Optimized from DSC00413.jpg (6000×4000) */
export const DSC00413 = ri(
  DSC00413_1600,
  `${DSC00413_640} 640w, ${DSC00413_1024} 1024w, ${DSC00413_1600} 1600w`,
  1600,
  1067,
  DSC00413_full,
);

/** Optimized from DSC00434.jpg (6000×4000) */
export const DSC00434 = ri(
  DSC00434_1600,
  `${DSC00434_640} 640w, ${DSC00434_1024} 1024w, ${DSC00434_1600} 1600w`,
  1600,
  1067,
  DSC00434_full,
);

/** Optimized from DSC00446.jpg (4937×3291) */
export const DSC00446 = ri(
  DSC00446_1600,
  `${DSC00446_640} 640w, ${DSC00446_1024} 1024w, ${DSC00446_1600} 1600w`,
  1600,
  1067,
  DSC00446_full,
);

/** Optimized from DSC00447.jpg (6000×4000) */
export const DSC00447 = ri(
  DSC00447_1600,
  `${DSC00447_640} 640w, ${DSC00447_1024} 1024w, ${DSC00447_1600} 1600w`,
  1600,
  1067,
  DSC00447_full,
);

/** Optimized from DSC00450.jpg (6000×4000) */
export const DSC00450 = ri(
  DSC00450_1600,
  `${DSC00450_640} 640w, ${DSC00450_1024} 1024w, ${DSC00450_1600} 1600w`,
  1600,
  1067,
  DSC00450_full,
);

/** Optimized from DSC00456.jpg (6000×4000) */
export const DSC00456 = ri(
  DSC00456_1600,
  `${DSC00456_640} 640w, ${DSC00456_1024} 1024w, ${DSC00456_1600} 1600w`,
  1600,
  1067,
  DSC00456_full,
);

/** Optimized from DSC00484.jpg (6000×4000) */
export const DSC00484 = ri(
  DSC00484_1600,
  `${DSC00484_640} 640w, ${DSC00484_1024} 1024w, ${DSC00484_1600} 1600w`,
  1600,
  1067,
  DSC00484_full,
);

/** Optimized from DSC00503.jpg (7008×4672) */
export const DSC00503 = ri(
  DSC00503_1600,
  `${DSC00503_640} 640w, ${DSC00503_1024} 1024w, ${DSC00503_1600} 1600w`,
  1600,
  1067,
  DSC00503_full,
);

/** Optimized from DSC00555.jpg (7008×4672) */
export const DSC00555 = ri(
  DSC00555_1600,
  `${DSC00555_640} 640w, ${DSC00555_1024} 1024w, ${DSC00555_1600} 1600w`,
  1600,
  1067,
  DSC00555_full,
);

/** Optimized from DSC00578.jpg (4000×6000) */
export const DSC00578 = ri(
  DSC00578_1600,
  `${DSC00578_640} 640w, ${DSC00578_1024} 1024w, ${DSC00578_1600} 1600w`,
  1600,
  2400,
  DSC00578_full,
);

/** Optimized from DSC00603.jpg (7008×4672) */
export const DSC00603 = ri(
  DSC00603_1600,
  `${DSC00603_640} 640w, ${DSC00603_1024} 1024w, ${DSC00603_1600} 1600w`,
  1600,
  1067,
  DSC00603_full,
);

/** Optimized from DSC00646.jpg (7008×4672) */
export const DSC00646 = ri(
  DSC00646_1600,
  `${DSC00646_640} 640w, ${DSC00646_1024} 1024w, ${DSC00646_1600} 1600w`,
  1600,
  1067,
  DSC00646_full,
);

/** Optimized from DSC00697.jpg (6000×4000) */
export const DSC00697 = ri(
  DSC00697_1600,
  `${DSC00697_640} 640w, ${DSC00697_1024} 1024w, ${DSC00697_1600} 1600w`,
  1600,
  1067,
  DSC00697_full,
);

/** Optimized from DSC00698-1-scaled.jpg (2560×1707) */
export const DSC00698_1_scaled = ri(
  DSC00698_1_scaled_1600,
  `${DSC00698_1_scaled_640} 640w, ${DSC00698_1_scaled_1024} 1024w, ${DSC00698_1_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00698_1_scaled_full,
);

/** Optimized from DSC00738.jpg (6000×4000) */
export const DSC00738 = ri(
  DSC00738_1600,
  `${DSC00738_640} 640w, ${DSC00738_1024} 1024w, ${DSC00738_1600} 1600w`,
  1600,
  1067,
  DSC00738_full,
);

/** Optimized from DSC00836.jpg (6000×4000) */
export const DSC00836 = ri(
  DSC00836_1600,
  `${DSC00836_640} 640w, ${DSC00836_1024} 1024w, ${DSC00836_1600} 1600w`,
  1600,
  1067,
  DSC00836_full,
);

/** Optimized from DSC00840-scaled.jpg (2560×1707) */
export const DSC00840_scaled = ri(
  DSC00840_scaled_1600,
  `${DSC00840_scaled_640} 640w, ${DSC00840_scaled_1024} 1024w, ${DSC00840_scaled_1600} 1600w`,
  1600,
  1067,
  DSC00840_scaled_full,
);

/** Optimized from DSC05081.png (1024×682) */
export const DSC05081 = ri(
  DSC05081_1600,
  `${DSC05081_640} 640w, ${DSC05081_1024} 1024w, ${DSC05081_1600} 1600w`,
  1024,
  682,
  DSC05081_full,
);

/** Optimized from DSC05087.png (1024×682) */
export const DSC05087 = ri(
  DSC05087_1600,
  `${DSC05087_640} 640w, ${DSC05087_1024} 1024w, ${DSC05087_1600} 1600w`,
  1024,
  682,
  DSC05087_full,
);

/** Optimized from DSC05089.png (1024×682) */
export const DSC05089 = ri(
  DSC05089_1600,
  `${DSC05089_640} 640w, ${DSC05089_1024} 1024w, ${DSC05089_1600} 1600w`,
  1024,
  682,
  DSC05089_full,
);

/** Optimized from DSC05112.png (1024×682) */
export const DSC05112 = ri(
  DSC05112_1600,
  `${DSC05112_640} 640w, ${DSC05112_1024} 1024w, ${DSC05112_1600} 1600w`,
  1024,
  682,
  DSC05112_full,
);

/** Optimized from DSC05112-hero.png (1024×630) */
export const DSC05112_hero = ri(
  DSC05112_hero_1600,
  `${DSC05112_hero_640} 640w, ${DSC05112_hero_1024} 1024w, ${DSC05112_hero_1600} 1600w`,
  1024,
  630,
  DSC05112_hero_full,
);

/** Optimized from DSC05175.png (1024×682) */
export const DSC05175 = ri(
  DSC05175_1600,
  `${DSC05175_640} 640w, ${DSC05175_1024} 1024w, ${DSC05175_1600} 1600w`,
  1024,
  682,
  DSC05175_full,
);

/** Optimized from DSC05124.jpg (4410×2940) */
export const DSC05124 = ri(
  DSC05124_1600,
  `${DSC05124_640} 640w, ${DSC05124_1024} 1024w, ${DSC05124_1600} 1600w`,
  1600,
  1067,
  DSC05124_full,
);

/** Optimized from DSC05124-1024_cleanup.webp (720×480) */
export const DSC05124_cleanup = ri(
  DSC05124_cleanup_1600,
  `${DSC05124_cleanup_640} 640w, ${DSC05124_cleanup_1024} 1024w, ${DSC05124_cleanup_1600} 1600w`,
  720,
  480,
  DSC05124_cleanup_full,
);

/** Optimized from DSC05126.jpg (4466×2977) */
export const DSC05126 = ri(
  DSC05126_1600,
  `${DSC05126_640} 640w, ${DSC05126_1024} 1024w, ${DSC05126_1600} 1600w`,
  1600,
  1067,
  DSC05126_full,
);

/** Optimized from DSC05143.jpg (4608×3072) */
export const DSC05143 = ri(
  DSC05143_1600,
  `${DSC05143_640} 640w, ${DSC05143_1024} 1024w, ${DSC05143_1600} 1600w`,
  1600,
  1067,
  DSC05143_full,
);

/** Optimized from DSC05150.jpg (4608×3072) */
export const DSC05150 = ri(
  DSC05150_1600,
  `${DSC05150_640} 640w, ${DSC05150_1024} 1024w, ${DSC05150_1600} 1600w`,
  1600,
  1067,
  DSC05150_full,
);

/** Optimized from DSC05222.jpg (4608×3072) */
export const DSC05222 = ri(
  DSC05222_1600,
  `${DSC05222_640} 640w, ${DSC05222_1024} 1024w, ${DSC05222_1600} 1600w`,
  1600,
  1067,
  DSC05222_full,
);

/** Optimized from Shushila_Institute_Of-removebg-preview-1-e1743436624699.png (524×127) */
export const Shushila_Institute_Of_removebg_preview_1_e1743436624699 = ri(
  Shushila_Institute_Of_removebg_preview_1_e1743436624699_1600,
  `${Shushila_Institute_Of_removebg_preview_1_e1743436624699_640} 640w, ${Shushila_Institute_Of_removebg_preview_1_e1743436624699_1024} 1024w, ${Shushila_Institute_Of_removebg_preview_1_e1743436624699_1600} 1600w`,
  524,
  127,
  Shushila_Institute_Of_removebg_preview_1_e1743436624699_full,
);

/** Optimized from awards-blood-donation.png (421×247) */
export const awards_blood_donation = ri(
  awards_blood_donation_1600,
  `${awards_blood_donation_640} 640w, ${awards_blood_donation_1024} 1024w, ${awards_blood_donation_1600} 1600w`,
  421,
  247,
  awards_blood_donation_full,
);

/** Optimized from awards-campus-facade.png (877×391) */
export const awards_campus_facade = ri(
  awards_campus_facade_1600,
  `${awards_campus_facade_640} 640w, ${awards_campus_facade_1024} 1024w, ${awards_campus_facade_1600} 1600w`,
  877,
  391,
  awards_campus_facade_full,
);

/** Optimized from awards-campus-run-team.png (612×268) */
export const awards_campus_run_team = ri(
  awards_campus_run_team_1600,
  `${awards_campus_run_team_640} 640w, ${awards_campus_run_team_1024} 1024w, ${awards_campus_run_team_1600} 1600w`,
  612,
  268,
  awards_campus_run_team_full,
);

/** Optimized from awards-ceremony-group.png (613×235) */
export const awards_ceremony_group = ri(
  awards_ceremony_group_1600,
  `${awards_ceremony_group_640} 640w, ${awards_ceremony_group_1024} 1024w, ${awards_ceremony_group_1600} 1600w`,
  613,
  235,
  awards_ceremony_group_full,
);

/** Optimized from awards-doctors-day-collage.png (510×345) */
export const awards_doctors_day_collage = ri(
  awards_doctors_day_collage_1600,
  `${awards_doctors_day_collage_640} 640w, ${awards_doctors_day_collage_1024} 1024w, ${awards_doctors_day_collage_1600} 1600w`,
  510,
  345,
  awards_doctors_day_collage_full,
);

/** Optimized from awards-tb-awareness.png (488×303) */
export const awards_tb_awareness = ri(
  awards_tb_awareness_1600,
  `${awards_tb_awareness_640} 640w, ${awards_tb_awareness_1024} 1024w, ${awards_tb_awareness_1600} 1600w`,
  488,
  303,
  awards_tb_awareness_full,
);

/** Optimized from awards-tb-day-group.png (405×190) */
export const awards_tb_day_group = ri(
  awards_tb_day_group_1600,
  `${awards_tb_day_group_640} 640w, ${awards_tb_day_group_1024} 1024w, ${awards_tb_day_group_1600} 1600w`,
  405,
  190,
  awards_tb_day_group_full,
);

/** Optimized from awards-tree-plantation-nursery.png (461×266) */
export const awards_tree_plantation_nursery = ri(
  awards_tree_plantation_nursery_1600,
  `${awards_tree_plantation_nursery_640} 640w, ${awards_tree_plantation_nursery_1024} 1024w, ${awards_tree_plantation_nursery_1600} 1600w`,
  461,
  266,
  awards_tree_plantation_nursery_full,
);

/** Optimized from chairman.jpeg (1024×678) */
export const chairman = ri(
  chairman_1600,
  `${chairman_640} 640w, ${chairman_1024} 1024w, ${chairman_1600} 1600w`,
  1024,
  678,
  chairman_full,
);

/** Optimized from coo.jpeg (388×390) */
export const coo = ri(
  coo_1600,
  `${coo_640} 640w, ${coo_1024} 1024w, ${coo_1600} 1600w`,
  388,
  390,
  coo_full,
);

/** Optimized from director.jpeg (1024×1024) */
export const director = ri(
  director_1600,
  `${director_640} 640w, ${director_1024} 1024w, ${director_1600} 1600w`,
  1024,
  1024,
  director_full,
);

/** Optimized from hnb-umeu-logo.png (300×308) */
export const hnb_umeu_logo = ri(
  hnb_umeu_logo_1600,
  `${hnb_umeu_logo_640} 640w, ${hnb_umeu_logo_1024} 1024w, ${hnb_umeu_logo_1600} 1600w`,
  300,
  308,
  hnb_umeu_logo_full,
);

/** Optimized from labs-collage.png (495×432) */
export const labs_collage = ri(
  labs_collage_1600,
  `${labs_collage_640} 640w, ${labs_collage_1024} 1024w, ${labs_collage_1600} 1600w`,
  495,
  432,
  labs_collage_full,
);

/** Optimized from transport-bus-collage.png (532×271) */
export const transport_bus_collage = ri(
  transport_bus_collage_1600,
  `${transport_bus_collage_640} 640w, ${transport_bus_collage_1024} 1024w, ${transport_bus_collage_1600} 1600w`,
  532,
  271,
  transport_bus_collage_full,
);

/** Optimized from transport-route-coverage-map.png (880×388) */
export const transport_route_coverage_map = ri(
  transport_route_coverage_map_1600,
  `${transport_route_coverage_map_640} 640w, ${transport_route_coverage_map_1024} 1024w, ${transport_route_coverage_map_1600} 1600w`,
  880,
  388,
  transport_route_coverage_map_full,
);

/** Optimized from hero-campus-life-collage.png (872×803) */
export const hero_campus_life_collage = ri(
  hero_campus_life_collage_1600,
  `${hero_campus_life_collage_640} 640w, ${hero_campus_life_collage_1024} 1024w, ${hero_campus_life_collage_1600} 1600w`,
  872,
  803,
  hero_campus_life_collage_full,
);

/** Optimized from hero-campus-life-collage-v2.png (876×726) */
export const hero_campus_life_collage_v2 = ri(
  hero_campus_life_collage_v2_1600,
  `${hero_campus_life_collage_v2_640} 640w, ${hero_campus_life_collage_v2_1024} 1024w, ${hero_campus_life_collage_v2_1600} 1600w`,
  876,
  726,
  hero_campus_life_collage_v2_full,
);

/** Optimized from logo-transparent.png (1600×219) */
export const logo_transparent = ri(
  logo_transparent_1600,
  `${logo_transparent_640} 640w, ${logo_transparent_1024} 1024w, ${logo_transparent_1600} 1600w`,
  1600,
  219,
  logo_transparent_full,
);

/** Optimized from logo-watermark.png (1600×219) */
export const logo_watermark = ri(
  logo_watermark_1600,
  `${logo_watermark_640} 640w, ${logo_watermark_1024} 1024w, ${logo_watermark_1600} 1600w`,
  1600,
  219,
  logo_watermark_full,
);

/** Optimized from logo.jpeg (1600×219) */
export const logo = ri(
  logo_1600,
  `${logo_640} 640w, ${logo_1024} 1024w, ${logo_1600} 1600w`,
  1600,
  219,
  logo_full,
);

/** Optimized from mission-skills-lab.png (395×486) */
export const mission_skills_lab = ri(
  mission_skills_lab_1600,
  `${mission_skills_lab_640} 640w, ${mission_skills_lab_1024} 1024w, ${mission_skills_lab_1600} 1600w`,
  395,
  486,
  mission_skills_lab_full,
);

/** Optimized from principal.jpeg (387×387) */
export const principal = ri(
  principal_1600,
  `${principal_640} 640w, ${principal_1024} 1024w, ${principal_1600} 1600w`,
  387,
  387,
  principal_full,
);

/** Optimized from sims-campus-entrance.jpeg (325×282) */
export const sims_campus_entrance = ri(
  sims_campus_entrance_1600,
  `${sims_campus_entrance_640} 640w, ${sims_campus_entrance_1024} 1024w, ${sims_campus_entrance_1600} 1600w`,
  325,
  282,
  sims_campus_entrance_full,
);

/** Optimized from sims-campus-lobby.jpeg (307×295) */
export const sims_campus_lobby = ri(
  sims_campus_lobby_1600,
  `${sims_campus_lobby_640} 640w, ${sims_campus_lobby_1024} 1024w, ${sims_campus_lobby_1600} 1600w`,
  307,
  295,
  sims_campus_lobby_full,
);

/** Optimized from sims-campus-signage.jpeg (325×296) */
export const sims_campus_signage = ri(
  sims_campus_signage_1600,
  `${sims_campus_signage_640} 640w, ${sims_campus_signage_1024} 1024w, ${sims_campus_signage_1600} 1600w`,
  325,
  296,
  sims_campus_signage_full,
);

/** Optimized from vice-chairperson.jpeg (781×678) */
export const vice_chairperson = ri(
  vice_chairperson_1600,
  `${vice_chairperson_640} 640w, ${vice_chairperson_1024} 1024w, ${vice_chairperson_1600} 1600w`,
  781,
  678,
  vice_chairperson_full,
);

/** Optimized from vision-inclusive-classroom.png (402×442) */
export const vision_inclusive_classroom = ri(
  vision_inclusive_classroom_1600,
  `${vision_inclusive_classroom_640} 640w, ${vision_inclusive_classroom_1024} 1024w, ${vision_inclusive_classroom_1600} 1600w`,
  402,
  442,
  vision_inclusive_classroom_full,
);

/** Optimized from awards-eia-plaque.png (317×212) */
export const awards_eia_plaque = ri(
  awards_eia_plaque_640,
  `${awards_eia_plaque_640} 317w`,
  317,
  212,
  awards_eia_plaque_full,
);

/** Optimized from awards-trophy-presentation.png (463×278) */
export const awards_trophy_presentation = ri(
  awards_trophy_presentation_640,
  `${awards_trophy_presentation_640} 463w`,
  463,
  278,
  awards_trophy_presentation_full,
);

/** Optimized from awards-campus-certificate-1.png (390×266) */
export const awards_campus_certificate_1 = ri(
  awards_campus_certificate_1_640,
  `${awards_campus_certificate_1_640} 390w`,
  390,
  266,
  awards_campus_certificate_1_full,
);

/** Optimized from awards-campus-certificate-2.png (232×197) */
export const awards_campus_certificate_2 = ri(
  awards_campus_certificate_2_640,
  `${awards_campus_certificate_2_640} 232w`,
  232,
  197,
  awards_campus_certificate_2_full,
);

/** Optimized from awards-campus-certificate-3.png (313×150) */
export const awards_campus_certificate_3 = ri(
  awards_campus_certificate_3_640,
  `${awards_campus_certificate_3_640} 313w`,
  313,
  150,
  awards_campus_certificate_3_full,
);

/** Optimized from awards-faculty-student-group.png (452×202) */
export const awards_faculty_student_group = ri(
  awards_faculty_student_group_640,
  `${awards_faculty_student_group_640} 452w`,
  452,
  202,
  awards_faculty_student_group_full,
);

/** Optimized from awards-tree-plantation-drive.png (417×275) */
export const awards_tree_plantation_drive = ri(
  awards_tree_plantation_drive_640,
  `${awards_tree_plantation_drive_640} 417w`,
  417,
  275,
  awards_tree_plantation_drive_full,
);

/** Optimized from awards-emerging-uttarakhand.png (552×362) */
export const awards_emerging_uttarakhand = ri(
  awards_emerging_uttarakhand_640,
  `${awards_emerging_uttarakhand_640} 552w`,
  552,
  362,
  awards_emerging_uttarakhand_full,
);

/** Lookup by original archive/original-images filename */
export const RESPONSIVE_BY_SOURCE: Record<string, ResponsiveImage> = {
  "12.png": img_12,
  "2 (1).png": img_2_1,
  "85cd0d1b-dedd-429d-9b22-297d0c72f2cc-scaled.jpg": img_85cd0d1b_dedd_429d_9b22_297d0c72f2cc_scaled,
  "9.png": img_9,
  "DSC00007.jpg": DSC00007,
  "DSC00009.jpg": DSC00009,
  "DSC00050.jpg": DSC00050,
  "DSC00051.jpg": DSC00051,
  "DSC00066-scaled.jpg": DSC00066_scaled,
  "DSC00066.jpg": DSC00066,
  "DSC00075-scaled.jpg": DSC00075_scaled,
  "DSC00080.jpg": DSC00080,
  "DSC00096.jpg": DSC00096,
  "DSC00114.jpg": DSC00114,
  "DSC00116.jpg": DSC00116,
  "DSC00118-scaled.jpg": DSC00118_scaled,
  "DSC00123.jpg": DSC00123,
  "DSC00134-scaled.jpg": DSC00134_scaled,
  "DSC00159.jpg": DSC00159,
  "DSC00161.jpg": DSC00161,
  "DSC00171.jpg": DSC00171,
  "DSC00177-scaled.jpg": DSC00177_scaled,
  "DSC00188.jpg": DSC00188,
  "DSC00259.jpg": DSC00259,
  "DSC00273.jpg": DSC00273,
  "DSC00287.jpg": DSC00287,
  "DSC00312.jpg": DSC00312,
  "DSC00317.jpg": DSC00317,
  "DSC00338.jpg": DSC00338,
  "DSC00365.jpg": DSC00365,
  "DSC00382.jpg": DSC00382,
  "DSC00408.jpg": DSC00408,
  "DSC00413.jpg": DSC00413,
  "DSC00434.jpg": DSC00434,
  "DSC00446.jpg": DSC00446,
  "DSC00447.jpg": DSC00447,
  "DSC00450.jpg": DSC00450,
  "DSC00456.jpg": DSC00456,
  "DSC00484.jpg": DSC00484,
  "DSC00503.jpg": DSC00503,
  "DSC00555.jpg": DSC00555,
  "DSC00578.jpg": DSC00578,
  "DSC00603.jpg": DSC00603,
  "DSC00646.jpg": DSC00646,
  "DSC00697.jpg": DSC00697,
  "DSC00698-1-scaled.jpg": DSC00698_1_scaled,
  "DSC00738.jpg": DSC00738,
  "DSC00836.jpg": DSC00836,
  "DSC00840-scaled.jpg": DSC00840_scaled,
  "DSC05081.png": DSC05081,
  "DSC05087.png": DSC05087,
  "DSC05089.png": DSC05089,
  "DSC05112.png": DSC05112,
  "DSC05112-hero.png": DSC05112_hero,
  "DSC05175.png": DSC05175,
  "DSC05124.jpg": DSC05124,
  "DSC05124-cleanup.png": DSC05124_cleanup,
  "DSC05126.jpg": DSC05126,
  "DSC05143.jpg": DSC05143,
  "DSC05150.jpg": DSC05150,
  "DSC05222.jpg": DSC05222,
  "Shushila_Institute_Of-removebg-preview-1-e1743436624699.png": Shushila_Institute_Of_removebg_preview_1_e1743436624699,
  "awards-blood-donation.png": awards_blood_donation,
  "awards-campus-facade.png": awards_campus_facade,
  "awards-campus-run-team.png": awards_campus_run_team,
  "awards-ceremony-group.png": awards_ceremony_group,
  "awards-doctors-day-collage.png": awards_doctors_day_collage,
  "awards-tb-awareness.png": awards_tb_awareness,
  "awards-tb-day-group.png": awards_tb_day_group,
  "awards-tree-plantation-nursery.png": awards_tree_plantation_nursery,
  "chairman.jpeg": chairman,
  "coo.jpeg": coo,
  "director.jpeg": director,
  "hnb-umeu-logo.png": hnb_umeu_logo,
  "hero-campus-life-collage.png": hero_campus_life_collage,
  "hero-campus-life-collage-v2.png": hero_campus_life_collage_v2,
  "labs-collage.png": labs_collage,
  "logo-transparent.png": logo_transparent,
  "logo-watermark.png": logo_watermark,
  "logo.jpeg": logo,
  "mission-skills-lab.png": mission_skills_lab,
  "principal.jpeg": principal,
  "sims-campus-entrance.jpeg": sims_campus_entrance,
  "sims-campus-lobby.jpeg": sims_campus_lobby,
  "sims-campus-signage.jpeg": sims_campus_signage,
  "transport-bus-collage.png": transport_bus_collage,
  "transport-route-coverage-map.png": transport_route_coverage_map,
  "vice-chairperson.jpeg": vice_chairperson,
  "vision-inclusive-classroom.png": vision_inclusive_classroom,
  "awards-eia-plaque.png": awards_eia_plaque,
  "awards-trophy-presentation.png": awards_trophy_presentation,
  "awards-campus-certificate-1.png": awards_campus_certificate_1,
  "awards-campus-certificate-2.png": awards_campus_certificate_2,
  "awards-campus-certificate-3.png": awards_campus_certificate_3,
  "awards-faculty-student-group.png": awards_faculty_student_group,
  "awards-tree-plantation-drive.png": awards_tree_plantation_drive,
  "awards-emerging-uttarakhand.png": awards_emerging_uttarakhand,
};
